version: '3'

services:
  webapp:
    build: .
    restart: unless-stopped
    depends_on:
      - db
      - broker
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST:?err}
      - RUN_AS_USER=${RUN_AS_USER:-1000}
      - RUN_AS_GROUP=${RUN_AS_GROUP:-1000}
      - APP_SECRET_KEY=${APP_SECRET_KEY:?err}
      - ARCHIVE_LOCATION=${ARCHIVE_LOCATION:?err}
      - INCOMING_LOCATION=${INCOMING_LOCATION:?err}
      - DIVA_LOCATION=${DIVA_LOCATION:?err}
      - DATA_LOCATION=${DATA_LOCATION:?err}
      - BACKUP_LOCATION=${BACKUP_LOCATION:?err}
      - APP_TMPDIR=${APP_TMPDIR:?err}
      - IIIF_IMAGE_BASE_URL=${IIIF_IMAGE_BASE_URL:?err}
      - IIIF_MANIF_BASE_URL=${IIIF_MANIF_BASE_URL:?err}
      - DB_POSTGRES_PW=${DB_POSTGRES_PW:?err}
      - RUN_MODE=${RUN_MODE:-production}
      - RUN_LOG_LEVEL=${RUN_LOG_LEVEL:-INFO}
    volumes:
      - static:/webapp/renamer/static/
      - ${LOCAL_TMPDIR:-/tmp}:${APP_TMPDIR:?err}
    networks:
      - internal
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_POSTGRES_PW:?err}
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - internal
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  broker:
    image: rabbitmq:3-alpine
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
    networks:
      - internal
      
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    labels:
      # use traefik proxy
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-net"
      # create router for our host
      - "traefik.http.routers.imageadmin.rule=Host(`${VIRTUAL_HOST:?err}`) && PathPrefix(`/imageadmin`)"
      # use TLS
      - "traefik.http.routers.imageadmin.entrypoints=https"
      - "traefik.http.routers.imageadmin.tls=true"
    volumes:
      - ./proxy/nginx/templates/:/etc/nginx/templates/:ro
      - static:/var/www/imageadmin/static/:ro
    networks:
      - internal
      - proxy-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  static:
  pgdata:

networks:
  internal:
  proxy-net:
    name: proxy-net
    external: true
