version: '3'

services:
  webapp:
    build: .
    environment:
      - RUN_AS_USER=${RUN_AS_USER:-1000:1000}
      - VIRTUAL_HOST=${VIRTUAL_HOST:?err}
    volumes:
      - static:/webapp/renamer/static/
      - ${PWD}/renamer.sqlite3:/webapp/renamer.sqlite3
      - ${PWD}/test-data/tusi:/tusi
      - /tmp:/opt/tmp
    ports:
      - "8000:8000"

  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/vhost.d/:/etc/nginx/vhost.d/:ro
      - static:/var/www/static/
    
volumes:
  static:
