version: '3'

services:
  webapp:
    build: .
    restart: always
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST:?err}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST:?err}
      - RUN_AS_USER=${RUN_AS_USER:-1000}
      - RUN_AS_GROUP=${RUN_AS_GROUP:-1000}
      - APP_SECRET_KEY=${APP_SECRET_KEY:?err}
      - ARCHIVE_LOCATION=${ARCHIVE_LOCATION:?err}
      - INCOMING_LOCATION=${INCOMING_LOCATION:?err}
      - DIVA_LOCATION=${DIVA_LOCATION:?err}
      - DATA_LOCATION=${DATA_LOCATION:?err}
      - BACKUP_LOCATION=${BACKUP_LOCATION:?err}
      - APP_TMPDIR=${APP_TMPDIR:?err}
      - IIIF_IMAGE_BASE_URL=${IIIF_IMAGE_BASE_URL:?err}
      - IIIF_MANIF_BASE_URL=${IIIF_MANIF_BASE_URL:?err}
      - DB_POSTGRES_PW=${DB_POSTGRES_PW:?err}
    volumes:
      - static:/webapp/renamer/static/
      - ${LOCAL_TMPDIR:-/tmp}:${APP_TMPDIR:?err}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:9-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_POSTGRES_PW:?err}
    volumes:
      - ./db/pgdata/:/var/lib/postgresql/data/
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
      
  proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/vhost.d/:/etc/nginx/vhost.d/:ro
      - ./proxy/certs/:/etc/nginx/certs/:ro
      - proxy-html:/usr/share/nginx/html/:ro
      - static:/var/www/static/:ro
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  certbot:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL:?err}
      # proxy should be discovered by label but it does not seem to work
      - NGINX_PROXY_CONTAINER=renamer_proxy_1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./proxy/vhost.d/:/etc/nginx/vhost.d/
      - ./proxy/certs/:/etc/nginx/certs/
      - proxy-html:/usr/share/nginx/html/
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
      
volumes:
  static:
  proxy-html:
