# Generated by Django 4.0.1 on 2022-01-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='direntry',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
